FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

RUN pip install --no-cache-dir gunicorn

COPY . /app/

EXPOSE 5000

CMD ["gunicorn", "--workers", "4", "--worker-class", "gevent", "--timeout", "120", "-b", "0.0.0.0:5000", "app:create_app()"]
